export const LIST_FIELDS = [
  "id",
  "name",
  "object_id",
  "status_primarix",
  "date_created",
  "date_updated",
  // Descriptions
  "descriptions_translations.translations_id.code",
  "descriptions_translations.teaser",
  "descriptions_translations.subline",
  // Country / place / state
  "country.id",
  "country.ISO",
  "country.id_primarix",
  "country.translations.name",
  "country.translations.translations_id.code",
  "state.id",
  "state.translations.name",
  "state.translations.translations_id.code",
  "place.id",
  "place.translations.name",
  "place.translations.translations_id.code",
  "location_tour32.id",
  "location_tour32.translations.name",
  "location_tour32.translations.translations_id.code",
];

export const DETAIL_FIELDS = [
  "id",
  "name",
  "object_id",
  "status",
  "status_primarix",
  "internal_remarks",
  "internal_remarks_reservation",
  "date_created",
  "date_updated",
  "user_created.id",
  "user_created.first_name",
  "user_created.last_name",
  "user_updated.id",
  "user_updated.first_name",
  "user_updated.last_name",
  "season",
  "operator_direct",
  "name_operator",
  "street",
  "street_number",
  "postcode",
  "phone_general",
  "phone_after_hours",
  "email_general",
  "website",
  "booking_channel",
  "email_booking",
  "service_provider_id_tour32",
  "main_service_provider_id_tour32",
  "supplier_product_code",
  "price_subline",
  "participants_min",
  "participants_max",
  "children_free_age",
  "children_free_number",
  "week_min_before_start",
  "image_badge_status",
  "image_badge_start_date",
  "image_badge_end_date",
  // Mobility advice text (m2o to global mobility_advice_text collection)
  "mobility_advice_text.id",
  // Descriptions translations
  "descriptions_translations.translations_id.code",
  "descriptions_translations.name_tour",
  "descriptions_translations.subline",
  "descriptions_translations.teaser",
  "descriptions_translations.at_a_glance",
  "descriptions_translations.from_to",
  "descriptions_translations.flights_recommended",
  "descriptions_translations.additional_recommendations",
  "descriptions_translations.description_supplementary",
  // Price info translations
  "price_info_translations.translations_id.code",
  "price_info_translations.services_included",
  "price_info_translations.services_not_included",
  "price_info_translations.services_optional",
  "price_info_translations.service_highlights",
  "price_info_translations.deviating_cancellation_terms",
  "price_info_translations.important_information",
  "price_info_translations.departure",
  "price_info_translations.children_policy",
  "price_info_translations.participants_text",
  "price_info_translations.price_info_supplementary",
  // Programme translations
  "programme_translations.translations_id.code",
  "programme_translations.tour_programme_disclaimer",
  "programme_translations.tour_programme",
  // Image badge translations
  "image_badge_translations.translations_id.code",
  "image_badge_translations.image_badge_teaser",
  "image_badge_translations.image_badge_details",
  // Geo
  "country.id",
  "country.ISO",
  "country.id_primarix",
  "country.translations.name",
  "country.translations.translations_id.code",
  "state.id",
  "state.translations.name",
  "state.translations.translations_id.code",
  "place.id",
  "place.translations.name",
  "place.translations.translations_id.code",
  "location_tour32.id",
  "location_tour32.translations.name",
  "location_tour32.translations.translations_id.code",
  // Flight
  "flight_service.id",
  "flight_service.name",
  "airlines.id",
  "airlines.name",
  "routes",
  // m2m
  "travel_categories.travel_categories_id.id",
  "travel_categories.travel_categories_id.name",
  "accommodation_types.accommodation_types_id.id",
  "accommodation_types.accommodation_types_id.label",
  "departure_airports.airports_id.id",
  "departure_airports.airports_id.name",
  "destinations.destinations_id.id",
  "destinations.destinations_id.translations.name",
  "destinations.destinations_id.translations.translations_id.code",
  "countries.countries_id.id",
  "countries.countries_id.translations.name",
  "countries.countries_id.translations.translations_id.code",
  "partner_selected.partner_id.primarix_id",
  // Categories (rooms-equivalent)
  "categories.id",
  "categories.tour_category_type.id",
  "categories.tour_category_type.name",
  "categories.category_supplier_code",
  "categories.category_from",
  "categories.translations.translations_id.code",
  "categories.translations.category_original",
  "categories.translations.category_text",
  // Dates
  "dates.id",
  "dates.available_from",
  "dates.available_to",
  "dates.departure_frequencies",
  "dates.trip_duration",
  // Occupancies
  "occupancies.id",
  "occupancies.occupancy.id",
  "occupancies.occupancy.name",
  "occupancies.occupancy_from",
  // Prices (buy_price only — no sell_price/translations wired for tours yet, see transformer note)
  "prices.id",
  "prices.tours_category_id",
  "prices.price_period_id",
  "prices.occupancy_id",
  "prices.buy_price",
  // Price periods
  "price_periods.id",
  "price_periods.price_period_start",
  "price_periods.price_period_end",
  "price_periods.price_period_from",
  // Media
  "media.directus_files_id.id",
  "media.directus_files_id.filename_download",
  "media.directus_files_id.draft_status",
  "media.directus_files_id.copyright",
  "media.directus_files_id.alt_text",
  "media.directus_files_id.expiry_date",
  "media.directus_files_id.is_map",
  "media.directus_files_id.tour32_export",
  "media.directus_files_id.dimensions_px",
  "media.directus_files_id.keyword_ids",
  "media.directus_files_id.folder.id",
  "media.directus_files_id.folder.name",
  "media.directus_files_id.translations.translations_id.code",
  "media.directus_files_id.translations.caption_i18n",
  // Surcharges — fetched separately to avoid Directus nested-translation resolution issues
  "surcharges.id",
];

export const SURCHARGE_FIELDS = [
  "id",
  "surcharge_booking_name",
  "px_source_id",
  "surcharge_type.designation",
  "calculation_method.designation",
  "translations.translations_id.code",
  "translations.surcharge_description",
];
