export const LIST_FIELDS = [
  "id",
  "object_id",
  "status_primarix",
  "date_created",
  "date_updated",
  // Descriptions — tours has no top-level `name` field; the display name only exists
  // per-language on descriptions_translations.name_tour.
  "descriptions_translations.translations_id.code",
  "descriptions_translations.name_tour",
  "descriptions_translations.teaser",
  "descriptions_translations.subline",
  // Country / place / state
  "country.id",
  "country.ISO",
  "country.id_primarix",
  "country.translations.name",
  "country.translations.translations_id.code",
  "state.id",
  "state.ISO",
  "state.translations.name",
  "state.translations.translations_id.code",
  "place.id",
  "place.translations.name",
  "place.translations.translations_id.code",
  "location_tour32.id",
  "location_tour32.name",
  // Departure dates (real o2m alias on tours is `departure_times`, NOT `dates`)
  "departure_times.id",
  "departure_times.available_from",
  "departure_times.available_to",
  "departure_times.trip_duration",
  "departure_times.departure_frequencies.trips_frequencies_id.id",
  "departure_times.departure_frequencies.trips_frequencies_id.name",
  // departures_text lives on the top-level tours alias `dates_translations` (→ tours_dates_translations)
  "dates_translations.translations_id.code",
  "dates_translations.departures_text",
  // geo (list): countries[] / destinations[] per the contract's TourListItem.geo shape
  "destinations.id",
  "destinations.destinations_id.id",
  "destinations.destinations_id.media_code",
  "destinations.destinations_id.translations.name",
  "destinations.destinations_id.translations.translations_id.code",
  "countries.countries_id.id",
  "countries.countries_id.ISO",
  "countries.countries_id.translations.name",
  "countries.countries_id.translations.translations_id.code",
  // Media fields for thumbnail
  "media.sort",
  "media.directus_files_id.id",
  "media.directus_files_id.primarix_picid",
  "media.directus_files_id.fotoware_file_name",
  "media.directus_files_id.filename_download",
  "media.directus_files_id.draft_status",
  "media.directus_files_id.copyright",
  "media.directus_files_id.primarix_workspace",
  "media.directus_files_id.alt_text",
  "media.directus_files_id.expiry_date",
  "media.directus_files_id.is_map",
  "media.directus_files_id.tour32_export",
  "media.directus_files_id.dimensions_px",
  "media.directus_files_id.keyword_ids",
  "media.directus_files_id.folder.id",
  "media.directus_files_id.folder.name",
  "media.directus_files_id.translations.translations_id.code",
  "media.directus_files_id.translations.caption_i18n",
];

export const DETAIL_FIELDS = [
  "id",
  "object_id",
  "status",
  "status_primarix",
  "partner_visibility",
  "internal_remarks",
  "internal_remarks_reservation",
  "date_created",
  "date_updated",
  "user_created.id",
  "user_created.first_name",
  "user_created.last_name",
  "user_updated.id",
  "user_updated.first_name",
  "user_updated.last_name",
  "season.id",
  "season.season",
  "sell_prices_status",
  "sell_prices_updated_at",
  "operator_direct",
  "operator_linked.id",
  "operator_linked.name_agency",
  "name_operator",
  "street",
  "street_number",
  "postcode",
  "phone_general",
  "phone_after_hours",
  "email_general",
  "website",
  "booking_channel",
  "email_booking",
  // Supplier contact (booking_partner M2O → agencies) — mirrors hotels' `booking` relation.
  "booking_partner.id",
  "booking_partner.name_agency",
  "booking_partner.phone_general",
  "booking_partner.phone_after_hours",
  "booking_partner.email_general",
  "booking_partner.website",
  "booking_partner.phone_reservation",
  "booking_partner.email_reservation",
  "booking_partner.contact_title",
  "booking_partner.contact_greeting",
  "booking_partner.contact_first_name",
  "booking_partner.contact_name",
  "service_provider_id_tour32",
  "main_service_provider_id_tour32",
  "supplier_product_code",
  "price_subline",
  "participants_min",
  "participants_max",
  "children_free_age",
  "children_free_number",
  "week_min_before_start",
  "image_badge_status",
  "image_badge_start_date",
  "image_badge_end_date",
  // Mobility advice text (m2o to global mobility_advice_text collection)
  "mobility_advice_text.id",
  "mobility_advice_text.hotel_translations.translations_id.code",
  "mobility_advice_text.hotel_translations.hotel_mobility_advice_text",
  // Descriptions translations
  "descriptions_translations.translations_id.code",
  "descriptions_translations.name_tour",
  "descriptions_translations.subline",
  "descriptions_translations.teaser",
  "descriptions_translations.at_a_glance",
  "descriptions_translations.from_to",
  "descriptions_translations.flights_recommended",
  "descriptions_translations.additional_recommendations",
  "descriptions_translations.description_supplementary",
  // Price info translations
  "price_info_translations.translations_id.code",
  "price_info_translations.services_included",
  "price_info_translations.services_not_included",
  "price_info_translations.services_optional",
  "price_info_translations.service_highlights",
  "price_info_translations.deviating_cancellation_terms",
  "price_info_translations.important_information",
  "price_info_translations.departure",
  "price_info_translations.children_policy",
  "price_info_translations.participants_text",
  "price_info_translations.price_info_supplementary",
  // Programme translations
  "programme_translations.translations_id.code",
  "programme_translations.tour_programme_disclaimer",
  "programme_translations.tour_programme",
  // Image badge translations
  "image_badge_translations.translations_id.code",
  "image_badge_translations.image_badge_teaser",
  "image_badge_translations.image_badge_details",
  // Geo
  "country.id",
  "country.ISO",
  "country.id_primarix",
  "country.translations.name",
  "country.translations.translations_id.code",
  "state.id",
  "state.ISO",
  "state.translations.name",
  "state.translations.translations_id.code",
  "place.id",
  "place.translations.name",
  "place.translations.translations_id.code",
  "location_tour32.id",
  "location_tour32.name",
  // Flight
  "flight_service.id",
  "flight_service.name",
  "airlines.id",
  "airlines.name",
  // Departure dates (real o2m alias on tours is `departure_times`, NOT `dates`)
  "departure_times.id",
  "departure_times.available_from",
  "departure_times.available_to",
  "departure_times.trip_duration",
  // departure_frequencies is an m2m on tours_dates → trips_frequencies (name holds the
  // frequency/weekday label). Always empty in current dev data.
  "departure_times.departure_frequencies.trips_frequencies_id.id",
  "departure_times.departure_frequencies.trips_frequencies_id.name",
  // departures_text lives on the top-level tours alias `dates_translations` (→ tours_dates_translations)
  "dates_translations.translations_id.code",
  "dates_translations.departures_text",
  // Travel routes (o2m → tours_routes; tour_departure / tour_arrival → places) —
  // resolve the localized place name for the contract's TourDate.departure_place.
  "travel_routes.id",
  "travel_routes.tour_departure.id",
  "travel_routes.tour_departure.translations.translations_id.code",
  "travel_routes.tour_departure.translations.name",
  "travel_routes.tour_arrival.id",
  "travel_routes.tour_arrival.translations.translations_id.code",
  "travel_routes.tour_arrival.translations.name",
  // Specials translations
  "specials_translations.translations_id.code",
  "specials_translations.specials",
  // m2m
  "travel_categories.travel_categories_id.id",
  "travel_categories.travel_categories_id.name",
  "travel_categories.travel_categories_id.status",
  // travel_categories_translations uses a raw `languages_code` string (e.g. "de-DE"),
  // not the usual translations_id → translations FK pattern used elsewhere.
  "travel_categories.travel_categories_id.translations.languages_code",
  "travel_categories.travel_categories_id.translations.name",
  "accommodation_types.accommodation_types_id.id",
  "accommodation_types.accommodation_types_id.label",
  "accommodation_types.accommodation_types_id.status",
  "departure_airports.airports_id.id",
  "departure_airports.airports_id.name",
  "departure_airports.airports_id.iata_code",
  "destinations.id",
  "destinations.destinations_id.id",
  "destinations.destinations_id.media_code",
  "destinations.destinations_id.translations.name",
  "destinations.destinations_id.translations.translations_id.code",
  "countries.countries_id.id",
  "countries.countries_id.ISO",
  "countries.countries_id.translations.name",
  "countries.countries_id.translations.translations_id.code",
  "countries.countries_id.destination_id.id",
  "countries.countries_id.destination_id.translations.name",
  "countries.countries_id.destination_id.translations.translations_id.code",
  "partner_selected.partner_id.id",
  "partner_selected.partner_id.primarix_id",
  "partner_selected.partner_id.label",
  "partner_selected.partner_id.partner_type",
  "partner_selected.partner_id.status",
  // Categories (rooms-equivalent)
  "categories.id",
  "categories.tour_category_type.id",
  "categories.tour_category_type.name",
  // tour_category_types_translations uses the standard translations_id → code pattern
  // (no raw `languages_code` column — that path doesn't exist and breaks /products/full).
  "categories.tour_category_type.translations.translations_id.code",
  "categories.tour_category_type.translations.name",
  "categories.category_supplier_code",
  "categories.category_from",
  "categories.translations.translations_id.code",
  // tours_categories_translations stores the localized name as `category_original` (not
  // `original`), and uses translations_id → code, not a raw `languages_code` column.
  "categories.translations.category_original",
  "categories.translations.category_text",
  // Occupancies
  "occupancies.id",
  "occupancies.occupancy.id",
  "occupancies.occupancy.name",
  "occupancies.occupancy.translations.name",
  "occupancies.occupancy.translations.translations_id.code",
  "occupancies.occupancy_from",
  // Prices (buy_price only — no sell_price/translations wired for tours yet, see transformer note)
  "prices.id",
  "prices.tours_category_id",
  "prices.price_period_id",
  "prices.occupancy_id",
  "prices.buy_price",
  // Price periods
  "price_periods.id",
  "price_periods.price_period_start",
  "price_periods.price_period_end",
  "price_periods.price_period_from",
  // Price calculation settings (margin/buy-type per language) — internal, feeds
  // categories[].prices margin/unit and top-level from_price, same as hotels'
  // hotel_prices/activeSettings.
  "price_calculation_translations.translations_id.code",
  "price_calculation_translations.buy_price_type",
  "price_calculation_translations.sell_price_type",
  "price_calculation_translations.percentage_type",
  "price_calculation_translations.provision_percentage",
  "price_calculation_translations.margin_percentage",
  "price_calculation_translations.exchange_rate",
  "price_calculation_translations.from_price",
  // Surcharge calculation settings (margin per language) — internal, feeds
  // surcharges[].margin.
  "surcharges_calculation_translations.translations_id.code",
  "surcharges_calculation_translations.surcharge_percentage_type",
  "surcharges_calculation_translations.surcharge_provision_percentage",
  "surcharges_calculation_translations.surcharge_margin_percentage",
  "surcharges_calculation_translations.surcharge_exchange_rate",
  // Media
  "media.sort",
  "media.directus_files_id.id",
  "media.directus_files_id.primarix_picid",
  "media.directus_files_id.fotoware_file_name",
  "media.directus_files_id.filename_download",
  "media.directus_files_id.draft_status",
  "media.directus_files_id.copyright",
  "media.directus_files_id.primarix_workspace",
  "media.directus_files_id.alt_text",
  "media.directus_files_id.expiry_date",
  "media.directus_files_id.is_map",
  "media.directus_files_id.tour32_export",
  "media.directus_files_id.dimensions_px",
  "media.directus_files_id.keyword_ids",
  "media.directus_files_id.folder.id",
  "media.directus_files_id.folder.name",
  "media.directus_files_id.translations.translations_id.code",
  "media.directus_files_id.translations.caption_i18n",
  // Surcharges — fetched separately to avoid Directus nested-translation resolution issues
  "surcharges.id",
];

export const SURCHARGE_FIELDS = [
  "id",
  "surcharge_booking_name",
  "px_source_id",
  "surcharge_type.id",
  "surcharge_type.designation",
  "calculation_method.id",
  "calculation_method.designation",
  "translations.translations_id.code",
  "translations.surcharge_description",
];
