export const LIST_FIELDS = [
  "id",
  "object_id",
  "status_primarix",
  "name_vehicle",
  "rental_type",
  "date_created",
  "date_updated",
  "descriptions_translations.translations_id.code",
  "descriptions_translations.teaser",
  "rental_company.id",
  "rental_company.name_company",
  "category.id",
  "category.name",
];

export const DETAIL_FIELDS = [
  "id",
  "object_id",
  "status_primarix",
  "partner_visibility",
  "rental_type",
  "name_vehicle",
  "supplier_product_code",
  "depot_availability",
  "drive_type",
  "persons_max",
  "suitcase_big",
  "suitcase_small",
  "image_badge_status",
  "image_badge_start_date",
  "image_badge_end_date",
  "date_created",
  "date_updated",
  "user_created.id",
  "user_created.first_name",
  "user_created.last_name",
  "user_updated.id",
  "user_updated.first_name",
  "user_updated.last_name",
  "rental_company.id",
  "rental_company.name_company",
  "category.id",
  "category.name",
  // Descriptions translations
  "descriptions_translations.translations_id.code",
  "descriptions_translations.teaser",
  // Image badge translations
  "image_badge_translations.translations_id.code",
  "image_badge_translations.image_badge_teaser",
  "image_badge_translations.image_badge_details",
  // m2m
  "depots_selected.rental_depots_id.id",
  "depots_selected.rental_depots_id.name_depot",
  "partner_selected.partner_id.primarix_id",
  // Media
  "media.directus_files_id.id",
  "media.directus_files_id.filename_download",
  "media.directus_files_id.draft_status",
  "media.directus_files_id.copyright",
  "media.directus_files_id.alt_text",
  "media.directus_files_id.expiry_date",
  "media.directus_files_id.is_map",
  "media.directus_files_id.tour32_export",
  "media.directus_files_id.dimensions_px",
  "media.directus_files_id.keyword_ids",
  "media.directus_files_id.folder.id",
  "media.directus_files_id.folder.name",
  "media.directus_files_id.translations.translations_id.code",
  "media.directus_files_id.translations.caption_i18n",
];

// camper_specs has no reverse alias on `vehicles` (O2O via camper_specs.vehicle, one_field
// is null) — fetched as a separate query filtered by vehicle id, same pattern as
// tours_surcharges/excursions_surcharges. Only populated for rental_type=Camper vehicles.
export const CAMPER_SPECS_FIELDS = [
  "id",
  "berths_adults",
  "berths_children",
  "seats_cab",
  "seats_living",
  "length_m",
  "width_m",
  "height_m",
  "interior_height_m",
  "transmission",
  "fuel_type",
  "engine_power_kw",
  "fuel_tank_l",
  "beds",
  "fridge_l",
  "freshwater_tank_l",
  "wastewater_tank_l",
  "highlights",
  "rating_botg",
  "equipment_features.availability",
  "equipment_features.feature.id",
  "equipment_features.feature.name",
  "equipment_features.feature.category",
  "equipment_features.feature.icon",
];
