import { defineInterface } from "@directus/extensions-sdk";
import InterfaceComponent from "./interface.vue";
import { DEFAULT_DOWNLOAD_FORMAT_PRESETS_JSON } from "./utils/downloadPresets.ts";

const DEFAULT_FILE_REVERSE_LINKS = JSON.stringify(
  [
    {
      junction_collection: "hotels_directus_files",
      file_field: "directus_files_id",
      fields: ["*", "hotels_id.*"],
      table_headers: ["id", "hotel id", "name"],
      table_paths: ["id", "hotels_id.id", "hotels_id.name"],
      section_title: "Hotels using this file",
      limit: 50,
    },
    {
      junction_collection: "hotels_directus_files",
      file_field: "cruises_files_id",
      fields: ["*", "cruises_id.*"],
      table_headers: ["id", "cruise id", "name"],
      table_paths: ["id", "cruises_id.id", "cruises_id.name"],
      section_title: "Cruises using this file",
      limit: 50,
    },
  ],
  null,
  2,
);

const DEFAULT_GEO_LEVELS = JSON.stringify(
  [
    {
      field: "place",
      collection: "places",
      label: "Place (City)",
      icon: "location_city",
    },
    { field: "state", collection: "states", label: "State", icon: "map" },
    {
      field: "region",
      collection: "regions_geo",
      label: "Region",
      icon: "terrain",
    },
    {
      field: "country",
      collection: "countries_geo",
      label: "Country",
      icon: "flag",
    },
    {
      field: "destination",
      collection: "destinations",
      label: "Destination",
      icon: "explore",
    },
    {
      field: "destination_cluster",
      collection: "destinations_cluster",
      label: "Destination Cluster",
      icon: "public",
    },
  ],
  null,
  2,
);

const DEFAULT_GEO_CASCADES = JSON.stringify(
  {
    place: [
      { fk: "state_id", to: "state" },
      { fk: "region_id", to: "region" },
      { fk: "country_id", to: "country" },
    ],
    state: [{ fk: "country_id", to: "country" }],
    region: [{ fk: "country_id", to: "country" }],
    country: [{ fk: "destination_id", to: "destination" }],
    destination: [{ fk: "destinations_cluster_id", to: "destination_cluster" }],
  },
  null,
  2,
);

const DEFAULT_GEO_FILTER_MAPPINGS = JSON.stringify(
  {
    place: [
      { fk: "country_id", from: "country" },
      { fk: "state_id", from: "state" },
      { fk: "region_id", from: "region" },
    ],
    state: [{ fk: "country_id", from: "country" }],
    region: [{ fk: "country_id", from: "country" }],
    destination: [{ fk: "countries_geo_id", from: "country" }],
    destination_cluster: [
      { fk: "destinations_cluster_id", from: "destination" },
    ],
  },
  null,
  2,
);

export default defineInterface({
  id: "media-uploader",
  name: "Media Uploader",
  icon: "image",
  description:
    "M2M file manager — upload, preview, delete and download files attached to any collection item.",
  component: InterfaceComponent,
  relational: true,
  types: ["alias"],
  localTypes: ["m2m", "files"],
  group: "relational",
  options: [
    {
      field: "allowed_types",
      name: "Allowed Types",
      type: "csv",
      meta: {
        width: "full",
        interface: "input",
        note: "Accepted MIME types (comma-separated). Use */* for all. E.g. image/*,application/pdf",
        options: { placeholder: "*/*" },
      },
      schema: { default_value: "*/*" },
    },
    {
      field: "max_file_size",
      name: "Max File Size (bytes)",
      type: "integer",
      meta: {
        width: "half",
        interface: "input",
        note: "Maximum file size in bytes. Leave empty for no limit.",
        options: { placeholder: "No limit" },
      },
      schema: { default_value: null },
    },
    {
      field: "thumbnail_size",
      name: "Thumbnail Size (px)",
      type: "integer",
      meta: {
        width: "half",
        interface: "input",
        note: "Width and height of each thumbnail in pixels.",
        options: { placeholder: "250" },
      },
      schema: { default_value: 250 },
    },
    {
      field: "readonly",
      name: "Read Only",
      type: "boolean",
      meta: {
        width: "half",
        interface: "boolean",
        note: "Disables upload, delete, and download.",
        options: { label: "Read Only" },
      },
      schema: { default_value: false },
    },
    {
      field: "delete_files",
      name: "Permanently Delete Files",
      type: "boolean",
      meta: {
        width: "half",
        interface: "boolean",
        note: "If enabled, permanently deletes the file from directus_files. Otherwise only removes the junction row.",
        options: { label: "Permanently Delete Files" },
      },
      schema: { default_value: false },
    },
    {
      field: "upload_area_folder",
      name: "Upload Area Folder ID",
      type: "string",
      meta: {
        width: "full",
        interface: "input",
        note: 'Folder ID used when the upload modal archive mode is "Upload Area". In that mode, files are uploaded directly into this configured interim folder instead of the normal folder picker selection.',
        options: { placeholder: "Directus folder ID for interim uploads" },
      },
      schema: { default_value: null },
    },
    {
      field: "file_reverse_links",
      name: "File details — reverse junction lookups",
      type: "json",
      meta: {
        interface: "input-code",
        options: { language: "json", template: DEFAULT_FILE_REVERSE_LINKS },
        note: "JSON array: for each entry, query /items/{junction_collection} where {file_field} equals the opened file id. Use fields as array or string (e.g. id,hotels_id.id,hotels_id.name). Optional: table_headers + table_paths arrays (same length) to render a custom table in File Details. Use [] to disable.",
        width: "full",
      },
      schema: { default_value: "[]" },
    },
    {
      field: "download_format_presets",
      name: "Download format presets",
      type: "json",
      meta: {
        interface: "input-code",
        options: {
          language: "json",
          template: DEFAULT_DOWNLOAD_FORMAT_PRESETS_JSON,
        },
        note: 'JSON array of download options: { "label", "format"?, "width"?, "height"?, "fit"?, "quality"? }. Used in thumbnail menus, download-all, and file details. Leave empty to use JPG, PNG, WebP, TIFF (same as before).',
        width: "full",
      },
      schema: { default_value: DEFAULT_DOWNLOAD_FORMAT_PRESETS_JSON },
    },
    {
      field: "geo_enabled",
      name: "Enable Geography",
      type: "boolean",
      meta: {
        width: "half",
        interface: "boolean",
        note: "Enable geography fields in the Upload modal. Selected IDs are written directly onto directus_files relation fields such as place, state, region, country, destination, and destination_cluster.",
        options: { label: "Enable Geography fields in Upload modal" },
      },
      schema: { default_value: true },
    },
    {
      field: "geo_levels",
      name: "Geography Levels Configuration",
      type: "json",
      meta: {
        interface: "input-code",
        options: { language: "json", template: DEFAULT_GEO_LEVELS },
        note: "JSON array of levels: {field, collection, label, icon?}. The `field` must match the directus_files relation field that should receive the selected ID.",
        width: "full",
      },
      schema: { default_value: DEFAULT_GEO_LEVELS },
    },
    {
      field: "geo_cascades",
      name: "Geography Cascade Mappings",
      type: "json",
      meta: {
        interface: "input-code",
        options: { language: "json", template: DEFAULT_GEO_CASCADES },
        note: "JSON object: cascade mapping. Key = source field name, value = array of {fk, to}, where `fk` is read from the selected source record and `to` is the target directus_files field key.",
        width: "full",
      },
      schema: { default_value: DEFAULT_GEO_CASCADES },
    },
    {
      field: "geo_filter_mappings",
      name: "Geography Filter Mappings",
      type: "json",
      meta: {
        interface: "input-code",
        options: { language: "json", template: DEFAULT_GEO_FILTER_MAPPINGS },
        note: "JSON object: upstream search filters. Key = field name, value = array of {fk, from}, where `fk` is the foreign key on the target collection and `from` is the selected upstream field.",
        width: "full",
      },
      schema: { default_value: DEFAULT_GEO_FILTER_MAPPINGS },
    },
    {
      field: "upload_status_field",
      name: "Upload Status Field",
      type: "string",
      meta: {
        width: "half",
        interface: "input",
        note: "Field name on directus_files to set on upload (e.g. directus_status). Leave empty to skip.",
        options: { placeholder: "directus_status" },
      },
      schema: { default_value: "directus_status" },
    },
    {
      field: "upload_status_value",
      name: "Upload Status Value",
      type: "string",
      meta: {
        width: "half",
        interface: "input",
        note: "Value written to the upload status field on each uploaded file. Default: draft.",
        options: { placeholder: "draft" },
      },
      schema: { default_value: "draft" },
    },
    {
      field: "geo_language_code",
      name: "Geography Language Code",
      type: "string",
      meta: {
        width: "half",
        interface: "input",
        options: { placeholder: "en-GB" },
      },
      schema: { default_value: "en-GB" },
    },
    {
      field: "geo_label_field",
      name: "Geography Label Field Path",
      type: "string",
      meta: {
        width: "half",
        interface: "input",
        note: "Dot-path for label, e.g. translations.name or name",
        options: { placeholder: "translations.name" },
      },
      schema: { default_value: "translations.name" },
    },
    {
      field: "section_label",
      name: "Section Label",
      type: "string",
      meta: {
        width: "half",
        interface: "system-input-translated-string",
        note: "Label shown in the media section header (e.g. 'Media', 'Photos', 'Documents'). Select a translation key from directus_translations.",
      },
      schema: { default_value: null },
    },
    {
      field: "empty_label",
      name: "Empty State Label",
      type: "string",
      meta: {
        width: "half",
        interface: "system-input-translated-string",
        note: "Text shown when no files are attached. Select a translation key from directus_translations.",
      },
      schema: { default_value: null },
    },
    {
      field: "upload_button_label",
      name: "Upload Button Label",
      type: "string",
      meta: {
        width: "half",
        interface: "system-input-translated-string",
        note: "Label for the upload button (e.g. 'Upload File', 'Add Photo'). Select a translation key from directus_translations.",
      },
      schema: { default_value: null },
    },
    {
      field: "add_existing_button_label",
      name: "Add Existing Button Label",
      type: "string",
      meta: {
        width: "half",
        interface: "system-input-translated-string",
        note: "Label for the add existing button. Select a translation key from directus_translations.",
      },
      schema: { default_value: null },
    },
    {
      field: "new_record_notice",
      name: "New Record Notice",
      type: "string",
      meta: {
        width: "full",
        interface: "system-input-translated-string",
        note: "Info notice shown on new (unsaved) records. Select a translation key from directus_translations.",
      },
      schema: { default_value: null },
    },
    // ── Shared upload modal labels (ml_) ──────────────────────────────
    {
      field: "upload_modal_title",
      name: "Upload Modal Title",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "upload_to_folder",
      name: "Upload To Folder Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "upload_drop_primary",
      name: "Drop Zone Primary Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "upload_drop_secondary",
      name: "Drop Zone Secondary Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "upload_selected_label",
      name: "Selected Files Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "upload_ready_count",
      name: "Ready To Upload Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "upload_clear_all",
      name: "Clear All Button",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "upload_geo_required_error",
      name: "Geo Required Error",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    // ── Shared folder dropdown labels (ml_) ───────────────────────────
    {
      field: "folder_root",
      name: "Folder Root Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "folder_loading",
      name: "Folder Loading Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "folder_no_access",
      name: "No Folders Available Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    // ── Shared geo labels (ml_) ───────────────────────────────────────
    {
      field: "geo_section_title",
      name: "Geo Section Title",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "geo_no_results",
      name: "Geo No Results Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "geo_loading",
      name: "Geo Loading Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    // ── Add Existing modal (media_uploader_) ──────────────────────────
    {
      field: "add_existing_title",
      name: "Add Existing Title",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "add_search_placeholder",
      name: "Add Existing Search Placeholder",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "add_no_files",
      name: "No Files Found Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "add_per_page",
      name: "Per Page Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "badge_linked",
      name: "Linked Badge",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "badge_draft",
      name: "Draft Badge",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "badge_expired",
      name: "Expired Badge",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "why_expired",
      name: "Why Expired Tooltip",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "add_to_album",
      name: "Add To Album Button",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "album_label",
      name: "Album Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "album_create_new",
      name: "Create New Album Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "album_name_placeholder",
      name: "New Album Name Placeholder",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "album_create_btn",
      name: "Create Album Button",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    // ── Share modal (media_uploader_) ─────────────────────────────────
    {
      field: "share_title",
      name: "Share Modal Title",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_hint",
      name: "Share Hint Text",
      type: "string",
      meta: { width: "full", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_password_label",
      name: "Share Password Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_password_placeholder",
      name: "Share Password Placeholder",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_expiry_label",
      name: "Share Expiry Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_email_label",
      name: "Share Email Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_email_placeholder",
      name: "Share Email Placeholder",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_create_btn",
      name: "Create Link Button",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_success",
      name: "Share Success Message",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_url_label",
      name: "Share URL Label",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "share_copy_url",
      name: "Copy URL Button",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    // ── Expiry dialog (media_uploader_) ───────────────────────────────
    {
      field: "expiry_title",
      name: "Expiry Dialog Title",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "expiry_body",
      name: "Expiry Body Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "expiry_warning",
      name: "Expiry Warning Text",
      type: "string",
      meta: { width: "full", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    // ── File Details Drawer (media_uploader_) ─────────────────────────
    {
      field: "drawer_tab_basic",
      name: "Drawer Basic Tab",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "drawer_tab_iptc",
      name: "Drawer IPTC Tab",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "drawer_tab_geo",
      name: "Drawer Geography Tab",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "drawer_iptc_title",
      name: "IPTC Caption Section Title",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "drawer_iptc_language",
      name: "IPTC Language Column",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "drawer_iptc_caption",
      name: "IPTC Caption Column",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    // ── File Media Extras Panel (media_uploader_) ─────────────────────
    {
      field: "extras_downloads",
      name: "Downloads Section Title",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "extras_download_original",
      name: "Download Original Button",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "extras_no_assignments",
      name: "No Assignments Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    // ── Linked Collections Dialog (media_uploader_) ───────────────────
    {
      field: "linked_title",
      name: "Linked Collections Title",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
    {
      field: "linked_empty",
      name: "No Linked Collections Text",
      type: "string",
      meta: { width: "half", interface: "system-input-translated-string" },
      schema: { default_value: null },
    },
  ],
});
