/**
 * Defines the raw fields retrieved from Directus for the hotels collection queries.
 * This determines only the database fetch scope. The final API response structure and audience
 * visibility (backoffice vs. web) are independently controlled by the transformer's `fieldDefs`.
 * Field lists are maintained per-collection to allow independent schema evolution.
 */
export const LIST_FIELDS = [
  // Base (px_source_id excluded — strip field, never in output)
  "id",
  "name",
  "object_id",
  "status_primarix",
  "date_created",
  "date_updated",
  "source_updated_at",
  // Descriptions
  "hotel_descriptions_translations.translations_id.code",
  "hotel_descriptions_translations.teaser",
  "hotel_descriptions_translations.description_short",
  // Country
  "country.id",
  "country.ISO",
  "country.id_primarix",
  "country.translations.name",
  "country.translations.translations_id.code",
  // State
  "state.id",
  "state.ISO",
  "state.translations.name",
  "state.translations.translations_id.code",
  // Region
  "region.id",
  "region.id_primarix",
  "region.translations.name",
  "region.translations.translations_id.code",
  // Place
  "place.id",
  "place.location_tour32",
  "place.translations.name",
  "place.translations.translations_id.code",
  //location_tour32
  "location_tour32.id",
  "location_tour32.name",
  // Key relations
  "hotel_classification.id",
  "hotel_classification.label",
  "hotel_group.id",
  "hotel_group.label",
  // Media fields for thumbnail
  "media.sort",
  "media.directus_files_id.id",
  "media.directus_files_id.primarix_picid",
  "media.directus_files_id.fotoware_file_name",
  "media.directus_files_id.filename_download",
  "media.directus_files_id.draft_status",
  "media.directus_files_id.copyright",
  "media.directus_files_id.primarix_workspace",
  "media.directus_files_id.translations.alt_text",
  "media.directus_files_id.expiry_date",
  "media.directus_files_id.is_map",
  "media.directus_files_id.tour32_export",
  "media.directus_files_id.dimensions_px",
  "media.directus_files_id.keyword_ids",
  "media.directus_files_id.folder.id",
  "media.directus_files_id.folder.name",
  "media.directus_files_id.translations.translations_id.code",
  "media.directus_files_id.translations.caption_i18n",
];

export const DETAIL_FIELDS = [
  // Base (px_source_id excluded — strip field)
  "id",
  "name",
  "season.id",
  "season.season",
  "object_id",
  "object_info",
  "internal_remarks",
  "street",
  "street_number",
  "zip_code",
  "phone_general",
  "phone_ah",
  "email_general",
  "website",
  "status_primarix",
  "date_created",
  "date_updated",
  "user_created.id",
  "user_created.first_name",
  "user_created.last_name",
  "user_updated.id",
  "user_updated.first_name",
  "user_updated.last_name",
  "id_tour_user",
  "haupt_id_tour_user",
  "booking_partner",
  "booking_email",
  "booking_info",
  "partner_type",
  "image_badge_status",
  "image_badge_start_date",
  "image_badge_end_date",
  // Hotel descriptions translations
  "hotel_descriptions_translations.translations_id.code",
  "hotel_descriptions_translations.subline_location",
  "hotel_descriptions_translations.teaser",
  "hotel_descriptions_translations.description_short",
  "hotel_descriptions_translations.description_surrounding",
  "hotel_descriptions_translations.description_rooms",
  "hotel_descriptions_translations.total_number_of_rooms",
  "hotel_descriptions_translations.remarks_arrival",
  "hotel_descriptions_translations.description_supplementary",
  // Price/service info translations (hotels_translations_3)
  "price_info_translations.translations_id.code",
  "price_info_translations.services_included",
  "price_info_translations.services_not_included",
  "price_info_translations.service_highlights",
  "price_info_translations.minimum_stay",
  "price_info_translations.minimum_stay_additions",
  "price_info_translations.deviating_cancelation_terms",
  "price_info_translations.children_policy",
  "price_info_translations.children_free_age",
  "price_info_translations.children_free_number",
  "price_info_translations.important_information",
  "price_info_translations.mobility_advice_text",
  "price_info_translations.price_infos_supplementary",
  // Hotel price settings per language — margin, buy entity, from_price (hotels_translations_1)
  "hotel_prices.translations_id.code",
  "hotel_prices.margin_percentage",
  "hotel_prices.buy_price_type",
  "hotel_prices.sell_price_type",
  "hotel_prices.percentage_type",
  "hotel_prices.provision_percentage",
  "hotel_prices.exchange_rate",
  "hotel_prices.from_price.room_prices_translations.translations_id.code",
  "hotel_prices.from_price.room_prices_translations.sell_price",
  // Country
  "country.id",
  "country.ISO",
  "country.id_primarix",
  "country.translations.name",
  "country.translations.translations_id.code",
  // State
  "state.id",
  "state.ISO",
  "state.translations.name",
  "state.translations.translations_id.code",
  // Region
  "region.id",
  "region.id_primarix",
  "region.translations.name",
  "region.translations.translations_id.code",
  // Place
  "place.id",
  "place.translations.name",
  "place.translations.translations_id.code",
  // location_tour32 (locations_tour32 collection — plain scalar name, no translations relation)
  "location_tour32.id",
  "location_tour32.name",
  // M2O relations
  "hotel_group.id",
  "hotel_group.label",
  "hotel_classification.id",
  "hotel_classification.label",
  "booking.id",
  "booking.name_agency",
  "booking.phone_general",
  "booking.phone_after_hours",
  "booking.email_general",
  "booking.website",
  "booking.phone_reservation",
  "booking.email_reservation",
  "booking.internal_remarks_reservation",
  "booking.contact_title",
  "booking.contact_greeting",
  "booking.contact_first_name",
  "booking.contact_name",
  "booking.it_code",
  "sell_prices_status",
  "sell_prices_updated_at",
  // M2M relations
  "accommodation_type.id",
  "accommodation_type.accommodation_types_id.id",
  "accommodation_type.accommodation_types_id.label",
  "partner.partner_id.id",
  "partner.partner_id.primarix_id",
  "partner.partner_id.label",
  "partner.partner_id.partner_type",
  "partner.partner_id.status",
  // Activities
  "hotel_activities.id",
  "hotel_activities.activities_id.id",
  "hotel_activities.activities_id.label",
  // Room categories with translations
  "room_categories.id",
  "room_categories.sort",
  "room_categories.room_category.id",
  "room_categories.room_category.translations.translations_id.code",
  "room_categories.room_category.translations.name",
  "room_categories.room_category_calc_type",
  "room_categories.room_category_booking_code",
  "room_categories.room_category_tour32_name",
  "room_categories.room_category_catering.id",
  "room_categories.room_category_catering.designation",
  "room_categories.status",
  "room_categories.publish_start",
  "room_categories.publish_end",
  "room_categories.translations.id",
  "room_categories.translations.translations_id.code",
  "room_categories.translations.room_category_additions",
  "room_categories.translations.room_category_description",
  // Room occupancies (name/value used to key rooms[].prices[].occupancies{})
  "room_occupancies.id",
  "room_occupancies.occupancies_id.id",
  "room_occupancies.occupancies_id.translations.translations_id.code",
  "room_occupancies.occupancies_id.translations.occupancy",
  // Price date windows
  "price_dates.id",
  "price_dates.name",
  "price_dates.start_date",
  "price_dates.end_date",
  "price_dates.from_price",
  "price_dates.status",
  "price_dates.publish_start",
  "price_dates.publish_end",
  // Room prices with sell prices per language
  "room_prices.id",
  "room_prices.room_category_id",
  "room_prices.price_date_id",
  "room_prices.room_occupancy_id",
  "room_prices.buy_price",
  "room_prices.date_updated",
  "room_prices.room_prices_translations.translations_id.code",
  "room_prices.room_prices_translations.sell_price",
  // Media / images
  "media.sort",
  "media.directus_files_id.id",
  "media.directus_files_id.primarix_picid",
  "media.directus_files_id.fotoware_file_name",
  "media.directus_files_id.filename_download",
  "media.directus_files_id.draft_status",
  "media.directus_files_id.copyright",
  "media.directus_files_id.primarix_workspace",
  "media.directus_files_id.translations.alt_text",
  "media.directus_files_id.expiry_date",
  "media.directus_files_id.is_map",
  "media.directus_files_id.tour32_export",
  "media.directus_files_id.dimensions_px",
  "media.directus_files_id.keyword_ids",
  "media.directus_files_id.folder.id",
  "media.directus_files_id.folder.name",
  "media.directus_files_id.translations.translations_id.code",
  "media.directus_files_id.translations.caption_i18n",
  // Image badge translations (hotels_translations_4)
  "image_badge_translations.translations_id.code",
  "image_badge_translations.image_badge_teaser",
  "image_badge_translations.image_badge_details",
  // Offers / specials (per-language JSON repeater — filtered in transformer)
  "specials_translations.translations_id.code",
  "specials_translations.specials",
  /* Surcharge margin settings per language. 
   * Note: This alias resolves to `hotels_surcharges_translations` for per-market settings.
   * Actual surcharge line items are fetched separately to avoid nested-translation resolution issues. */
  "surcharges.translations_id.code",
  "surcharges.surcharge_percentage_type",
  "surcharges.surcharge_provision_percentage",
  "surcharges.surcharge_margin_percentage",
  "surcharges.surcharge_exchange_rate",
];

export const CHILD_RC_FIELDS = [
  /* Contains only unique child row fields; rich metadata is always inherited from the parent. */
  "id",
  "sharedId",
  "sort",
];

export const SURCHARGE_FIELDS = [
  "id",
  "name",
  "px_source_id",
  "buy_price",
  "status",
  "publish_start",
  "publish_end",
  "translations.translations_id.code",
  "translations.surcharge_description",
  "translations.sell_price",
  "translations.surcharge_booking_name",
  "translations.surcharge_type.id",
  "translations.surcharge_type.designation",
  "translations.surcharge_catering.id",
  "translations.surcharge_catering.designation",
  "translations.surcharge_calc_type.id",
  "translations.surcharge_calc_type.designation",
];
