export const LIST_FIELDS = [
  "id",
  "object_id",
  "status_primarix",
  "date_created",
  "date_updated",
  // excursions has no top-level `name` field — the display name only exists
  // per-language on descriptions_translations.name_excursion.
  "descriptions_translations.translations_id.code",
  "descriptions_translations.name_excursion",
  "descriptions_translations.teaser",
  "descriptions_translations.subline",
  "country.id",
  "country.ISO",
  "country.id_primarix",
  "country.translations.name",
  "country.translations.translations_id.code",
  "state.id",
  "state.ISO",
  "state.translations.name",
  "state.translations.translations_id.code",
  "place.id",
  "place.translations.name",
  "place.translations.translations_id.code",
  "destination.id",
  "destination.media_code",
  "destination.translations.name",
  "destination.translations.translations_id.code",
  // Media fields for thumbnail
  "media.sort",
  "media.directus_files_id.id",
  "media.directus_files_id.primarix_picid",
  "media.directus_files_id.fotoware_file_name",
  "media.directus_files_id.filename_download",
  "media.directus_files_id.draft_status",
  "media.directus_files_id.copyright",
  "media.directus_files_id.primarix_workspace",
  "media.directus_files_id.alt_text",
  "media.directus_files_id.expiry_date",
  "media.directus_files_id.is_map",
  "media.directus_files_id.tour32_export",
  "media.directus_files_id.dimensions_px",
  "media.directus_files_id.keyword_ids",
  "media.directus_files_id.folder.id",
  "media.directus_files_id.folder.name",
  "media.directus_files_id.translations.translations_id.code",
  "media.directus_files_id.translations.caption_i18n",
];

export const DETAIL_FIELDS = [
  "id",
  "object_id",
  "status_primarix",
  "internal_remarks",
  "internal_remarks_reservation",
  "date_created",
  "date_updated",
  "user_created.id",
  "user_created.first_name",
  "user_created.last_name",
  "user_updated.id",
  "user_updated.first_name",
  "user_updated.last_name",
  "season.id",
  "season.season",
  "sell_prices_status",
  "sell_prices_updated_at",
  "object_info_primarix",
  "operator_direct",
  "operator_linked.id",
  "operator_linked.name_agency",
  "name_operator",
  "street",
  "street_number",
  "postcode",
  "phone_general",
  "phone_after_hours",
  "email_general",
  "website",
  "booking_channel",
  "email_booking",
  "booking_partner.id",
  "booking_partner.name_agency",
  "booking_partner.phone_reservation",
  "booking_partner.email_reservation",
  "booking_partner.contact_title",
  "booking_partner.contact_greeting",
  "booking_partner.contact_first_name",
  "booking_partner.contact_name",
  "id_service_provider_tour32",
  "id_main_service_provider_tour32",
  "supplier_product_code",
  "price_subline",
  "participants_min",
  "participants_max",
  "children_free_age",
  "children_free_number",
  "week_min_before_start",
  "image_badge_status",
  "image_badge_start_date",
  "image_badge_end_date",
  "mobility_advice_text.id",
  "mobility_advice_text.hotel_translations.translations_id.code",
  "mobility_advice_text.hotel_translations.hotel_mobility_advice_text",
  // Descriptions translations
  "descriptions_translations.translations_id.code",
  "descriptions_translations.name_excursion",
  "descriptions_translations.subline",
  "descriptions_translations.teaser",
  "descriptions_translations.excursion_programme_disclaimer",
  "descriptions_translations.excursion_programme",
  "descriptions_translations.recommendations",
  "descriptions_translations.description_supplementary",
  // Price info translations
  "price_infos_translations.translations_id.code",
  "price_infos_translations.services_included",
  "price_infos_translations.services_not_included",
  "price_infos_translations.deviating_cancellation_terms",
  "price_infos_translations.children_policy",
  "price_infos_translations.participants_text",
  "price_infos_translations.additional_information",
  "price_infos_translations.price_info_supplementary",
  // Price calculation — authoritative from_price pointer + margin/exchange config
  "price_calculation_translations.translations_id.code",
  "price_calculation_translations.buy_price_type",
  "price_calculation_translations.sell_price_type",
  "price_calculation_translations.percentage_type",
  "price_calculation_translations.provision_percentage",
  "price_calculation_translations.margin_percentage",
  "price_calculation_translations.exchange_rate",
  "price_calculation_translations.from_price",
  // Surcharges calculation / margin per language
  "surcharges_translations.translations_id.code",
  "surcharges_translations.surcharge_percentage_type",
  "surcharges_translations.surcharge_provision_percentage",
  "surcharges_translations.surcharge_margin_percentage",
  "surcharges_translations.surcharge_exchange_rate",
  // Departure dates (real o2m alias on excursions is `departure_times` → excursions_dates)
  "departure_times.id",
  "departure_times.available_from",
  "departure_times.available_to",
  // Frequency is an m2m on excursions_dates → trips_frequencies (name holds the label)
  "departure_times.departure_frequencies.trips_frequencies_id.id",
  "departure_times.departure_frequencies.trips_frequencies_id.name",
  // Departure/arrival places come from the first travel route (excursions_routes → places)
  "travel_routes.tour_departure.id",
  "travel_routes.tour_departure.translations.translations_id.code",
  "travel_routes.tour_departure.translations.name",
  "travel_routes.tour_arrival.id",
  "travel_routes.tour_arrival.translations.translations_id.code",
  "travel_routes.tour_arrival.translations.name",
  // departures_text lives on the top-level excursions alias `dates_translations` (→ excursions_dates_translations)
  "dates_translations.translations_id.code",
  "dates_translations.departures_text",
  // Specials content is stored per-language as JSON on `specials_translations` (→ excursions_specials_translations)
  "specials_translations.translations_id.code",
  "specials_translations.specials",
  // Image badge translations
  "image_badge_translations.translations_id.code",
  "image_badge_translations.image_badge_teaser",
  "image_badge_translations.image_badge_details",
  // Geo
  "country.id",
  "country.ISO",
  "country.id_primarix",
  "country.translations.name",
  "country.translations.translations_id.code",
  "state.id",
  "state.ISO",
  "state.translations.name",
  "state.translations.translations_id.code",
  "place.id",
  "place.translations.name",
  "place.translations.translations_id.code",
  "location_tour32.id",
  "location_tour32.name",
  "destination.id",
  "destination.media_code",
  "destination.translations.name",
  "destination.translations.translations_id.code",
  // m2m
  "travel_categories.travel_categories_id.id",
  "travel_categories.travel_categories_id.name",
  "countries.countries_id.id",
  "countries.countries_id.ISO",
  "countries.countries_id.translations.name",
  "countries.countries_id.translations.translations_id.code",
  "partner_selected.partner_id.primarix_id",
  // Categories
  "categories.id",
  "categories.excursion_category_type.id",
  "categories.excursion_category_type.name",
  "categories.excursion_category_type.translations.name",
  "categories.excursion_category_type.translations.translations_id.code",
  "categories.category_supplier_code",
  "categories.category_from",
  "categories.translations.translations_id.code",
  "categories.translations.category_text",
  "categories.translations.category_original",
  // Price periods
  "price_periods.id",
  "price_periods.price_period_start",
  "price_periods.price_period_end",
  "price_periods.price_period_from",
  // Price categories (occupancy-equivalent)
  "price_categories.id",
  "price_categories.price_category.id",
  "price_categories.price_category.name",
  "price_categories.price_category.translations.name",
  "price_categories.price_category.translations.translations_id.code",
  "price_categories.price_category_from",
  // Prices — with per-language sell price
  "prices.id",
  "prices.excursions_category_id",
  "prices.price_period_id",
  "prices.excursions_price_category_id",
  "prices.buy_price",
  "prices.excursions_prices_translations.translations_id.code",
  "prices.excursions_prices_translations.sell_price",
  // Media
  "media.sort",
  "media.directus_files_id.id",
  "media.directus_files_id.primarix_picid",
  "media.directus_files_id.fotoware_file_name",
  "media.directus_files_id.filename_download",
  "media.directus_files_id.draft_status",
  "media.directus_files_id.copyright",
  "media.directus_files_id.primarix_workspace",
  "media.directus_files_id.alt_text",
  "media.directus_files_id.expiry_date",
  "media.directus_files_id.is_map",
  "media.directus_files_id.tour32_export",
  "media.directus_files_id.dimensions_px",
  "media.directus_files_id.keyword_ids",
  "media.directus_files_id.folder.id",
  "media.directus_files_id.folder.name",
  "media.directus_files_id.translations.translations_id.code",
  "media.directus_files_id.translations.caption_i18n",
  // Surcharges — fetched separately to avoid Directus nested-translation resolution issues
  "surcharges_items.id",
];

export const SURCHARGE_FIELDS = [
  "id",
  "name",
  "px_source_id",
  "buy_price",
  "status",
  "publish_start",
  "publish_end",
  "surcharge_type.id",
  "surcharge_type.designation",
  "calculation_method.id",
  "calculation_method.designation",
  "translations.translations_id.code",
  "translations.surcharge_booking_name",
  "translations.surcharge_description",
  "translations.sell_price",
];
